remoteclient:
  container_name: remoteclient
  image: brianmedia/remoteclient
  ports:
    - "6789:6789"
  environment:
    - PUID=1000
    - PGID=1000
    - UMASK=002
    - TZ=Etc/UTC
    - DEBUG=yes
  volumes:
    - /opt/remoteclient:/config
